inherit_gem:
  rubocop-bsm:
    - default.yml
inherit_mode:
  merge:
    - Exclude

AllCops:
  TargetRubyVersion: "2.6"

Naming/FileName:
  Exclude:
    - "lib/datadog-notifications.rb"
    - "datadog-notifications.gemspec"
